### ISSUE TITLE
Placeholder for search bar?

### ISSUE THREAD

**Issue by Blakeinstein** [ckotzbauer/simple-tree-component#780]
Is it possible to expose an API from setting the placeholder for the search bar?

**Comment by ckotzbauer** [comment]
It would be possible to add an optional `placeholder` to the search-input, yes. Would it be ok to simply add this possibility to the options-object or do you need to change the watermark afterwards (when the component is already initialized)?

**Comment by Blakeinstein** [comment]
I think adding a field in options should be more than enough.

**Comment by ckotzbauer** [comment]
Good. Would you mind to create a PR for that? If not, I maybe find time in the next few days to implement this.

**Comment by Blakeinstein** [comment]
Should the default be an empty string? or Should I just set the default to "Search". And should I include the built files in the PR?

**Comment by ckotzbauer** [comment]
> Should the default be an empty string? or Should I just set the default to "Search"

I think a empty string is better here.

> And should I include the built files in the PR?

No.

**Comment by Blakeinstein** [comment]
Should not be a chore to merge 🤔
