### ISSUE TITLE
Set selected class regression

### ISSUE THREAD

**Issue by Blakeinstein** [ckotzbauer/simple-tree-component#782]
I want to programmatically set a node as selected.

```ts
const simpleTree = simpleTree('tree', 'view', {nodes: [...]});
const node = simpleTree.getNode(fileValue);
console.log(node.selected); // true
simpleTree.setSelected(node);
console.log(node.selected); // true
```
The node has selected true(its the first node in the tree).
And set Selection does nothing.
Furthermore the dom element doesnt have the selected class.

**Comment by Blakeinstein** [comment]
Additionally, hrefs on the docs are broken for me. It could really benefit from some usage examples :p

**Comment by ckotzbauer** [comment]
Are there any errors in the console? Which browser and OS do you use?

In the API docs there are several broken links, as this is autogenerated with typedoc which works not always correct. I have to fix this in the future. Are there other broken links in the rest of the docs?

Are there any specific use-case examples which you were searching for in the docs?

**Comment by Blakeinstein** [comment]
Well mostly style guide.

Anyways, I am on Firefox on windows 11 and no error logs.

**Comment by ckotzbauer** [comment]
> Well mostly style guide.

I can try to improve the style docs.

Okay, I assume that the error also occurs with Chrome or Firefox on Windows 10?
Did you set the `selected` attribute for the corresponding tree-node object to `true` on component-initialization? I wonder that the first `console.log` gives `true` as result.
Anyway, I can't reproduce the issue with the example fiddle. Could you try to create a small repro fiddle?

**Comment by Blakeinstein** [comment]
I think the first console.log() was a regression from my side. Fixed that. But I can repro the not selected issue here.

https://codesandbox.io/s/elegant-bush-fq0kz

You can see that the class was not added.

**Comment by ckotzbauer** [comment]
The second `console.log` will never give `selected == true` without re-fetching the object from the component. The reason for this is, that all methods which return `TreeNode`s are returning a copy of the object, so the object-reference is broken by design. (I will document this behavior)

I can reproduce the issue with your repro, thanks! I will dig deeper into that, when I have time. It seems that internal callbacks are not called as expected.

Currently the "selectionChanged" event fires for both selection and deselection. The only way to "ignore" deselection is to leave the function when the `.selected` property is `false` for the given item. In the future it would be possible to split the events or change the event-payload to cancel it. But this would be a breaking change, so I do not expect this for 1.x

**Comment by Blakeinstein** [comment]
yes but internally that would remove the selected class still?

**Comment by ckotzbauer** [comment]
When you deselect a node, then the selected class is removed, yes. Which behavior do you want to achieve? Multi-selection?

**Comment by Blakeinstein** [comment]
Well I am using this as a file tree component alongside monaco editor. Ideally I want a file to be selected at all times, (The active file in the editor)

**Comment by ckotzbauer** [comment]
Okay, so this is definitely single-selection. When you have one file selected and click on another, it is a deselection of the first file and a selection of the second. But you should only receive one event (for the selection). This is triggered through the click on the new file.
When you do not click on another file but the same (selected) file again, the selection is removed. This cannot be avoided.

What do you mean with "that would remove the selected class still"? The selected-class will always be present for items which are selected until you change its selection state.

I was able to set a item to selected state directly on component initialization via the `selected` property of the tree-node with your repro example. This would make the (currently broken) `setSelected` call unnecessary and would achieve your requirement of always having one item selected. Is this correct?

**Comment by Blakeinstein** [comment]
> I was able to set a item to selected state directly on component initialization via the `selected` property of the tree-node with your repro example. 

This actually resolves my use case requirement. Didn't know you could do this :P.

> This would make the (currently broken) `setSelected` call unnecessary and would achieve your requirement of always having one item selected. Is this correct?

Not exactly. I dont want the user to be able to `deselect` an item. Leaving no selected items in the tree.

**Comment by ckotzbauer** [comment]
> This actually resolves my use case requirement. Didn't know you could do this :P.

Great!

> Not exactly. I dont want the user to be able to deselect an item. Leaving no selected items in the tree.

That's what I said is currently not possible. There's no way right now to cancel or reject a event e.g. for deselection. I can create an issue for this for a future 2.x release.

**Comment by Blakeinstein** [comment]
Maybe a fix for the programmatic approach? I can always reselect the old node on null

**Comment by ckotzbauer** [comment]
>  I can always reselect the old node on null

Yes.

The only way I have in mind to avoid a deselection of a node (without selecting another) without a breaking-change would be a new config-flag. This would be possible, even it is not a really fancy solution 😆

**Comment by Blakeinstein** [comment]
Looked into the code, this is probably why.
https://github.com/ckotzbauer/simple-tree-component/blob/0d16ad46b1a889a728d7f90428238e73477e9e95/src/data/data-service.ts#L225-L227

The set Selected api, is used for checkboxes only?

**Comment by ckotzbauer** [comment]
Yes, this could be the logic error. :+1:
No, `setSelected` should work in all modes.

**Comment by Blakeinstein** [comment]
I do not clearly understand the code here, will it be possible to push in a resolution soon?

**Comment by ckotzbauer** [comment]
I think I will have time on weekend to investigate on the `setSelected` problem.
