### ISSUE TITLE
Introduce cancelable events to prevent default-selection-behaviour

### ISSUE THREAD

**Issue by ckotzbauer** [ckotzbauer/simple-tree-component#788]
Ref: #782
/kind feature

**Comment by Blakeinstein** [comment]
Instead of a config flag, can we have a callback handler approach? Or maybe a custom event, that can be preventDefault() 'ed? I don't exactly have a use-case in mind, but maybe if someone wants to run some kind of validation on node selection?

**Comment by ckotzbauer** [comment]
Thanks for your detailed ideas.

## Callback
Personally I won't prefer this approach, as it would break the current behavour and the user has to write code to let the behaviour happen he want's to achive usually. An alternative to the callback would be a boolean return-value, with `false` indicating the prevention (`true` as default return-value).

## Cancelable Event
This would be the approach which mostly follows web-standards and the way the user expects things to work. Nevertheless it would be also a breaking change when arguments are restructured. If the event-object is only a additional parameter, it would be easier.


In general, I have to analyse the codebase as I have to flip code-blocks to make this possible. Now, the event is fired at the end, when all logic and selections are done.

**Comment by Blakeinstein** [comment]
The cancel-able event would really be great, since you take a reference to the dom element in the initializer. This would make it compatible with frameworks, as well where you have syntax for event listeners, or even standard js using eventListeners, I was almost expecting this to be a web component, before I saw the code :p

**Comment by ckotzbauer** [comment]
The component is data-driven rather than DOM driven. This is the reason why the DOM as such is not the dominant part. But I won't say that it is not a web-component, only because it does not use DOM-based events. 😉

**Comment by ckotzbauer** [comment]
hm, I'm trying to implement this. It's not that easy, as the "selectionChanged" event is currently fired at the end, when all logic is done. Then it is clear, which item(s) are selected and which not, so the event-payload can be the new selected-array.

To make cancellation possible, I have to fire the event first to know if the user wants to abort the event. But it's not easy possible to "predict" the final node-selection without really executing the logic, which is then hard to rollback if cancellation appears.

I guess this is hard to implement prior a 2.0 release...

**Comment by Blakeinstein** [comment]
you can fire a custom event and wait for it to be rejected, if the event bubbles without rejection, then you just execute the logic?

**Comment by ckotzbauer** [comment]
Yes, I can do that. But the only information I can give to this event is the selection-change of the node which was clicked (or (de)selected in another way). But I can't present the final list of selection-changes (including subsequent changes which happen implicit by the node which was clicked). Maybe this is not enough information to the developer to decide if the event should be cancelled or not. Maybe only a selection of a specific node should be avoided. When clicking this node directly, this would be possible, but if the parent is selected (which maybe can implicitly selects its childs) it would not be possible to reject this selection...
